<?php
/**
 * Illia Neiman
 *
 * NOTICE OF LICENSE
 *
 * According to LICENCE file you are not allowed to copy, use or recreate this file in any ways.
 * Specially for eCommerce usage.
 *
 * @category Ineiman
 * @package TikTok
 * @copyright Copyright (c) 2021-current Ineiman (https://github.com/illyaneiman)
 * @email kg.illya.ney@gmail.com
 */

/**
 * @var \Ineiman\TikTok\Block\Track\Tiktok $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
/** @codingStandardsIgnoreFile */

$tiktokPixelId = $escaper->escapeHtml($block->getPixelId());
$customerEntityId = $escaper->escapeHtml($block->getCustomerEntityId());
$customerEmail = $escaper->escapeHtml($block->getCustomerEmail());
$customerPhone = $escaper->escapeHtml($block->getCustomerTelephone());
?>
<!-- TikTok Pixel Code Start -->
<?php $scriptString = <<<script
    !function (w, d, t) {
      w.TiktokAnalyticsObject=t;var ttq=w[t]=w[t]||[];ttq.methods=["page","track","identify","instances","debug","on","off","once","ready","alias","group","enableCookie","disableCookie","holdConsent","revokeConsent","grantConsent"],ttq.setAndDefer=function(t,e){t[e]=function(){t.push([e].concat(Array.prototype.slice.call(arguments,0)))}};for(var i=0;i<ttq.methods.length;i++)ttq.setAndDefer(ttq,ttq.methods[i]);ttq.instance=function(t){for(
    var e=ttq._i[t]||[],n=0;n<ttq.methods.length;n++)ttq.setAndDefer(e,ttq.methods[n]);return e},ttq.load=function(e,n){var r="https://analytics.tiktok.com/i18n/pixel/events.js",o=n&&n.partner;ttq._i=ttq._i||{},ttq._i[e]=[],ttq._i[e]._u=r,ttq._t=ttq._t||{},ttq._t[e]=+new Date,ttq._o=ttq._o||{},ttq._o[e]=n||{};n=document.createElement("script")
    ;n.type="text/javascript",n.async=!0,n.src=r+"?sdkid="+e+"&lib="+t;e=document.getElementsByTagName("script")[0];e.parentNode.insertBefore(n,e)};


      ttq.load('{$tiktokPixelId}');
      ttq.page();
    }(window, document, 'ttq');
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false); ?>
<!-- TikTok Pixel Code End -->

<!-- Identify Customer Code Start -->
<?php $identifyCustomerScriptString = <<<script
    let email = '{$customerEmail}';
    let phoneNumber = '{$customerPhone}';
    let entityId = '{$customerEntityId}';

    if (email && phoneNumber && entityId) {
        ttq.identify({
            email: email,
            phone_number: phoneNumber,
            external_id: entityId
        });
    }
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $identifyCustomerScriptString, false); ?>
<!-- Identify Customer Code End -->

<?= $block->getChildHtml(); ?>
